//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomInfoOutlookAddIn.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoomInfoOutlookAddIn.Properties.LanguageResources", typeof(LanguageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ABSENT ähnelt.
        /// </summary>
        internal static string DropDown_ItemLabel_Occupancy_Absent {
            get {
                return ResourceManager.GetString("DropDown_ItemLabel_Occupancy_Absent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BUSY ähnelt.
        /// </summary>
        internal static string DropDown_ItemLabel_Occupancy_Busy {
            get {
                return ResourceManager.GetString("DropDown_ItemLabel_Occupancy_Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FREE ähnelt.
        /// </summary>
        internal static string DropDown_ItemLabel_Occupancy_Free {
            get {
                return ResourceManager.GetString("DropDown_ItemLabel_Occupancy_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LOCKED ähnelt.
        /// </summary>
        internal static string DropDown_ItemLabel_Occupancy_Locked {
            get {
                return ResourceManager.GetString("DropDown_ItemLabel_Occupancy_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OCCUPIED ähnelt.
        /// </summary>
        internal static string DropDown_ItemLabel_Occupancy_Occupied {
            get {
                return ResourceManager.GetString("DropDown_ItemLabel_Occupancy_Occupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PRESENT ähnelt.
        /// </summary>
        internal static string DropDown_ItemLabel_Occupancy_Present {
            get {
                return ResourceManager.GetString("DropDown_ItemLabel_Occupancy_Present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Management ähnelt.
        /// </summary>
        internal static string Management_GroupLabel {
            get {
                return ResourceManager.GetString("Management_GroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recycle ähnelt.
        /// </summary>
        internal static string RecycleButton_Label {
            get {
                return ResourceManager.GetString("RecycleButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rooms ähnelt.
        /// </summary>
        internal static string Rooms_GroupLabel {
            get {
                return ResourceManager.GetString("Rooms_GroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string Settings_GroupLabel {
            get {
                return ResourceManager.GetString("Settings_GroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Roominfo ähnelt.
        /// </summary>
        internal static string Tab_Label {
            get {
                return ResourceManager.GetString("Tab_Label", resourceCulture);
            }
        }
    }
}
